project:
  type: website

website:
  title: "SCB Users Group"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - guides.qmd
      - FAQs.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



